export const images = {
  chef: require('./chef.png'),
  tasting: require('./tasting.png'),
  place: require('./undraw_navigation_lytx.png'),
  loading: require('./i-loading.png'),
  error: require('./i-happy.png'),
  warning: require('./undraw_warning_cyit.png'),
  dfWallpaper: require('./i-party.png'),
  iBooking: require('./i-booking.png'),
  iCalendar: require('./i-calendar.png'),
  iHappy: require('./i-happy.png'),
  iWashHand: require('./undraw_wash_hands_nwl2.png'),
  iUpload: require('./undraw_uploading_go67.png'),
  addImgPlaceholder: require('./add_image_placeholder.png'),
  iMale: require('./undraw_male_avatar_323b.png'),
  iProfilePic: require('./i-profile.png'),
  iEmpty: require('./i-empty.png'),
  tets: require('./i-empty.png'),
}
export type ImagesTypes = keyof typeof images
